'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const {capturePrivateInputs, assertPrivateClassification, equalExpandedInputs, regular} = require('../tools/lib/matching/private_inputs');
const fixtureRoot = path.join(root, 'build/private-input-tests');
fs.mkdirSync(fixtureRoot, {recursive:true});
const fixture = fs.mkdtempSync(path.join(fixtureRoot, 'input-'));
fs.mkdirSync(path.join(fixture, 'include')); fs.mkdirSync(path.join(fixture, 'config'));
fs.writeFileSync(path.join(fixture, 'include/header.h'), 'int a;\n');
fs.writeFileSync(path.join(fixture, 'config/flags.json'), '{"flag":"x"}');
const capture = () => capturePrivateInputs({root:fixture,directories:['include','config'],files:['current.json']});
let count = 0;
function check(name, fn) {fn(); count++; console.log('PASS '+name);}
check('unchanged shared inputs', ()=>capture().assertUnchanged());
check('same-size header drift rejects', ()=>{const seal=capture();fs.writeFileSync(path.join(fixture,'include/header.h'),'int b;\n');assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('same-size config/flag drift rejects', ()=>{const seal=capture();fs.writeFileSync(path.join(fixture,'config/flags.json'),'{"flag":"y"}');assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('new include shadow rejects', ()=>{const seal=capture();fs.writeFileSync(path.join(fixture,'include/shadow.h'),'int x;');assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('missing CURRENT becomes present rejects', ()=>{const seal=capture();fs.writeFileSync(path.join(fixture,'current.json'),'{}');assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('CURRENT replacement rejects', ()=>{const seal=capture();fs.writeFileSync(path.join(fixture,'current.json'),'[]');assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('header disappearance rejects', ()=>{const seal=capture();fs.unlinkSync(path.join(fixture,'include/shadow.h'));assert.throws(()=>seal.assertUnchanged(),/changed/);});
check('root traversal rejected', ()=>assert.throws(()=>capturePrivateInputs({root:fixture,directories:['../outside'],files:[]}),/escapes/));
const policy = {class:'PURE_C',sourceSha256:'source',compilationInput:{bytes:3,sha256:'one'},dependencies:[{path:'include/header.h'}],preprocessor:{flags:['-P']}};
check('approved repository headers', ()=>assertPrivateClassification(policy,fixture));
check('local header dependency rejects', ()=>assert.throws(()=>assertPrivateClassification({...policy,dependencies:[{path:'build/w1/header.h'}]},fixture),/approved include/));
check('header traversal rejects', ()=>assert.throws(()=>assertPrivateClassification({...policy,dependencies:[{path:'include/../config/flags.json'}]},fixture),/approved include/));
check('UNKNOWN does not become PURE_C', ()=>assert.throws(()=>assertPrivateClassification({...policy,class:'UNKNOWN'},fixture),/unavailable/));
check('HYBRID remains allowed as HYBRID', ()=>assertPrivateClassification({...policy,class:'HYBRID_C'},fixture));
check('authored/snapshot matching expanded bytes', ()=>equalExpandedInputs(policy,{...policy},{compilationInputBytes:()=>Buffer.from('one')}));
check('expanded byte mismatch rejects despite equal metadata', ()=>assert.throws(()=>equalExpandedInputs(policy,{...policy},{compilationInputBytes:v=>Buffer.from(v===policy?'one':'two')}),/preprocessing differs/));
check('source location macro changed compilation identity rejects', ()=>assert.throws(()=>equalExpandedInputs(policy,{...policy,compilationInput:{bytes:3,sha256:'two'}},{compilationInputBytes:()=>Buffer.from('one')}),/preprocessing differs/));
check('private class cannot differ from snapshot', ()=>assert.throws(()=>equalExpandedInputs(policy,{...policy,class:'HYBRID_C'},{compilationInputBytes:()=>Buffer.from('one')}),/preprocessing differs/));
check('junction input rejected', ()=>{const alias=path.join(fixture,'alias');fs.symlinkSync(path.join(fixture,'include'),alias,'junction');assert.throws(()=>regular(path.join(alias,'header.h')),/redirected|aliased/);fs.unlinkSync(alias);});
console.log(`Private input tests: ${count} passed; fixtures retained at ${fixture}`);
