#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

function usage() {
  console.log(`Usage: node tools/generate_external_git_pin.js --repo <git-dir> --commit <commit> --remote <name> --out <json> [--check]

Generates a deterministic manifest of one external Git commit without checking
it out or copying its source tree. Gitlinks include their pinned object IDs and
the URLs declared by that commit's .gitmodules file. --check compares the
generated bytes with an existing manifest and writes nothing.`);
}

function parseArgs(argv) {
  const args = { repo: null, commit: null, remote: null, out: null, check: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') {
      usage();
      process.exit(0);
    } else if (arg === '--repo') {
      args.repo = path.resolve(argv[++i]);
    } else if (arg === '--commit') {
      args.commit = argv[++i];
    } else if (arg === '--remote') {
      args.remote = argv[++i];
    } else if (arg === '--out') {
      args.out = path.resolve(argv[++i]);
    } else if (arg === '--check') {
      args.check = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  for (const required of ['repo', 'commit', 'remote', 'out']) {
    if (!args[required]) throw new Error(`Missing required --${required}`);
  }
  return args;
}

function runGit(repo, gitArgs) {
  const result = spawnSync('git', ['-C', repo, ...gitArgs], {
    encoding: 'utf8',
    windowsHide: true,
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.status !== 0) {
    const output = [result.stdout, result.stderr].filter(Boolean).join('');
    throw new Error(`git ${gitArgs.join(' ')} failed\n${output}`);
  }
  return result.stdout;
}

function parseGitmodules(text) {
  const modules = [];
  let current = null;
  for (const line of text.replace(/\r\n/g, '\n').split('\n')) {
    const section = line.match(/^\[submodule "(.+)"\]$/);
    if (section) {
      current = { name: section[1], path: null, url: null };
      modules.push(current);
      continue;
    }
    const field = line.match(/^\s*(path|url)\s*=\s*(.+?)\s*$/);
    if (current && field) current[field[1]] = field[2];
  }
  for (const module of modules) {
    if (!module.path || !module.url) {
      throw new Error(`Incomplete .gitmodules entry: ${JSON.stringify(module)}`);
    }
  }
  return modules;
}

function parseTree(text, modulesByPath) {
  const records = text.split('\0').filter(Boolean);
  return records.map((record) => {
    const match = record.match(/^([0-9]{6}) ([^ ]+) ([0-9a-f]{40})\s+([0-9-]+)\t([\s\S]+)$/);
    if (!match) throw new Error(`Unexpected git ls-tree record: ${record}`);
    const [, mode, type, object, size, filePath] = match;
    const entry = {
      mode,
      type,
      object,
      sizeBytes: size === '-' ? null : Number(size),
      path: filePath,
    };
    if (mode === '160000') {
      const module = modulesByPath.get(filePath);
      if (!module) throw new Error(`Gitlink has no .gitmodules entry: ${filePath}`);
      entry.submoduleUrl = module.url;
    }
    return entry;
  });
}

function buildManifest(args) {
  const commit = runGit(args.repo, ['rev-parse', `${args.commit}^{commit}`]).trim();
  const remoteUrl = runGit(args.repo, ['remote', 'get-url', args.remote]).trim();
  const metadata = runGit(args.repo, [
    'show',
    '-s',
    '--format=%H%x00%T%x00%P%x00%an%x00%ae%x00%aI%x00%cn%x00%ce%x00%cI%x00%s',
    commit,
  ]).replace(/\r?\n$/, '').split('\0');
  if (metadata.length !== 10) throw new Error(`Unexpected commit metadata field count: ${metadata.length}`);

  let gitmodulesText = '';
  try {
    gitmodulesText = runGit(args.repo, ['show', `${commit}:.gitmodules`]);
  } catch (err) {
    if (!String(err.message).includes('does not exist')) throw err;
  }
  const modules = parseGitmodules(gitmodulesText);
  const modulesByPath = new Map(modules.map((module) => [module.path, module]));
  const treeText = runGit(args.repo, ['ls-tree', '-r', '-l', '-z', '--full-tree', commit]);
  const entries = parseTree(treeText, modulesByPath);
  const gitlinks = entries.filter((entry) => entry.mode === '160000');
  const blobs = entries.filter((entry) => entry.type === 'blob');
  const unboundSubmoduleDeclarations = modules.filter(
    (module) => !gitlinks.some((entry) => entry.path === module.path),
  );

  const manifest = {
    schemaVersion: 1,
    kind: 'external-git-tree-pin',
    source: {
      remoteName: args.remote,
      remoteUrl,
      commit: metadata[0],
      tree: metadata[1],
      parents: metadata[2] ? metadata[2].split(' ') : [],
      author: { name: metadata[3], email: metadata[4], date: metadata[5] },
      committer: { name: metadata[6], email: metadata[7], date: metadata[8] },
      subject: metadata[9],
    },
    summary: {
      entries: entries.length,
      blobs: blobs.length,
      gitlinks: gitlinks.length,
      blobBytes: blobs.reduce((sum, entry) => sum + entry.sizeBytes, 0),
    },
    submodules: gitlinks.map((entry) => ({
      path: entry.path,
      url: entry.submoduleUrl,
      commit: entry.object,
    })),
    entries,
  };
  if (unboundSubmoduleDeclarations.length) {
    manifest.unboundSubmoduleDeclarations = unboundSubmoduleDeclarations;
  }
  return manifest;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const serialized = `${JSON.stringify(buildManifest(args), null, 2)}\n`;
  if (args.check) {
    if (!fs.existsSync(args.out)) throw new Error(`Manifest not found: ${args.out}`);
    const existing = fs.readFileSync(args.out, 'utf8');
    if (existing !== serialized) throw new Error(`Manifest differs: ${args.out}`);
    console.log(`PASS external Git pin matches ${args.out}`);
    return;
  }
  fs.mkdirSync(path.dirname(args.out), { recursive: true });
  fs.writeFileSync(args.out, serialized);
  console.log(`Wrote external Git pin: ${args.out}`);
}

main();
