#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { ROOT } = require('./lib/phase7_conventional');
const {
  loadWorkbenchModel,
  publicTarget,
  resolveTarget,
} = require('./lib/matching/target_model');
const {
  initializeStore,
  requestStore,
} = require('./lib/matching/store');
const {
  compileCandidate,
  prepareCompilerSession,
  syncTargets,
} = require('./lib/matching/compiler');
const { compareMips, targetMetrics } = require('./lib/matching/mips_analysis');
const {
  comparisonAlgorithmIdentity,
  loadDiagnosticEnvironment,
} = require('./lib/matching/diagnostic_link');
const {
  assertCandidateComparisonInputs,
  assertCandidateComparisonResult,
  compareCaseCfg,
  resolveCandidateComparisonContract,
} = require('./lib/matching/case_cfg');
const { prepareAndCompile, resolveM2c } = require('./lib/matching/m2c');
const { runSweep, summarizeEnsemble } = require('./lib/matching/sweep');
const { buildFamilyAtlas } = require('./lib/matching/family');
const { buildContextIndex, storeTargetContext } = require('./lib/matching/context');
const { rankTargets } = require('./lib/matching/rank');
const { compareProbes, runProbe } = require('./lib/matching/probe');

const VALUE_OPTIONS = new Set([
  'limit', 'source', 'candidate', 'variant', 'm2c-root', 'set', 'max-size',
  'lane', 'note', 'research-compiler', 'passes', 'jobs', 'case-map',
  'actual-dispatch', 'actual-body', 'output', 'actual-tail',
]);
const REPEAT_OPTIONS = new Set(['variant', 'actual-tail']);
let comparisonQueryProvenanceCache = null;

function comparisonQueryProvenance() {
  if (!comparisonQueryProvenanceCache) {
    const session = prepareCompilerSession();
    comparisonQueryProvenanceCache = {
      comparisonAlgorithmId: comparisonAlgorithmIdentity(),
      diagnosticCurrentFingerprint: session.context.currentFingerprint,
      diagnosticEnvironmentId: loadDiagnosticEnvironment(session).identity,
    };
  }
  return comparisonQueryProvenanceCache;
}

function usage() {
  console.log(`Usage: node tools/match.js <command> [arguments]

Core:
  doctor [--m2c-root <path>]
  inspect <symbol> [--limit N]
  history <symbol> [--limit N] [--include-details]
  best <symbol> [--limit N] [--include-details]
  watch <symbol> --source <candidate.c>
  classify <candidate-id> [--include-details] [--include-source]
  compare <candidate-id> <candidate-id>
  case-cfg <candidate-id> --case-map <map.json> --actual-dispatch <offset> --actual-body <offset>
           --actual-tail <name=offset>... [--output <report.json>]
  preserve <candidate-id> --note <reason>

Generation:
  prepare <symbol> [--variant <ruleset>]... [--with-context|--no-context] [--runtime] [--no-compile] [--m2c-root <path>]
  sweep [--set <name>] [--variant <ruleset>]... [--max-size N] [--leaf-only] [--limit N] [--jobs N]
        [--include-solved] [--with-context|--no-context] [--runtime] [--no-compile] [--m2c-root <path>]
  sweep-status [--limit N] [--include-targets]

Research:
  family build
  family <symbol> [--limit N] [--include-members]
  family list [--tier <tier>] [--limit N] [--include-members]
  context <symbol> [--runtime] [--include-context]
  rank [--lane leverage|batch|hard-tail] [--limit N] [--skip-families]
  rank --explain <symbol>
  probe <symbol> [--source <file> | --candidate <id>] [--passes a,b] [--research-compiler <file>]
  probe compare <left-report.json> <right-report.json>

Routine generated outputs stay under build/matching; preserve is the explicit
tracked candidate/dossier export. Add --json for structured output.
Use explicit --include-details, --include-members, --include-context, or
--include-targets when the bounded default is not enough.

prepare and sweep use the complete configured ruleset ensemble when --variant is
omitted; repeat --variant to select a subset. Bare sweep selects every currently
unsolved ordinary target, so normally provide --set, --max-size, or --limit.
The fixed set name is smallest-leaves-200. Context is generated by default but
is passed to m2c only with --with-context.`);
}

function parseArgs(argv) {
  const positional = [];
  const options = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith('--')) { positional.push(arg); continue; }
    const name = arg.slice(2);
    if (VALUE_OPTIONS.has(name) || name === 'tier' || name === 'explain') {
      const value = argv[++index];
      if (!value || value.startsWith('--')) throw new Error(`--${name} requires a value`);
      if (REPEAT_OPTIONS.has(name)) {
        options[name] = options[name] || [];
        options[name].push(value);
      } else {
        if (['case-map', 'actual-dispatch', 'actual-body', 'output'].includes(name)
            && Object.prototype.hasOwnProperty.call(options, name)) {
          throw new Error(`--${name} may not be repeated`);
        }
        options[name] = value;
      }
    } else if ([
      'json', 'no-context', 'with-context', 'no-compile', 'leaf-only', 'runtime', 'skip-families',
      'include-targets', 'include-details', 'include-source', 'include-members', 'include-context', 'include-solved',
    ].includes(name)) {
      options[name] = true;
    } else throw new Error(`unknown option: --${name}`);
  }
  return { positional, options };
}

function numeric(value, label, defaultValue = null) {
  if (value === undefined || value === null) return defaultValue;
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) throw new Error(`${label} must be a positive integer`);
  return parsed;
}

function nonnegativeInteger(value, label) {
  if (Number.isSafeInteger(value) && value >= 0) return value;
  if (typeof value === 'string' && /^(?:0x[0-9a-f]+|[0-9]+)$/i.test(value.trim())) {
    const parsed = Number.parseInt(value, 0);
    if (Number.isSafeInteger(parsed) && parsed >= 0) return parsed;
  }
  throw new Error(`${label} must be a nonnegative integer`);
}

function actualTailMap(values) {
  const grouped = new Map();
  for (const value of values || []) {
    const match = /^([^=]+)=(0x[0-9a-f]+|[0-9]+)$/i.exec(value);
    if (!match) throw new Error('--actual-tail requires name=offset');
    const name = match[1].trim();
    if (!name) throw new Error('--actual-tail name is empty');
    if (!grouped.has(name)) grouped.set(name, []);
    grouped.get(name).push(nonnegativeInteger(match[2], '--actual-tail offset'));
  }
  return [...grouped].map(([name, offsets]) => ({ name, offsets }));
}

function print(value, options = {}) {
  if (options.json) {
    console.log(JSON.stringify(value, null, 2));
    return;
  }
  if (typeof value === 'string') console.log(value);
  else console.log(JSON.stringify(value, null, 2));
}

function portableSourcePath(file) {
  const relative = path.relative(ROOT, file);
  if (relative && relative !== '..' && !relative.startsWith(`..${path.sep}`)) return relative.replace(/\\/g, '/');
  return `<external>/${path.basename(file)}`;
}

function boundedSweepResult(result, includeTargets = false, targetLimit = 20) {
  if (!result?.summary) return result;
  const hasTargets = Array.isArray(result.summary.targets);
  const targets = hasTargets ? result.summary.targets : [];
  const sampleLimit = Math.min(targetLimit, 3);
  const ruleSetNames = result.selector?.variants || result.summary.ensemble?.ruleSets?.map((row) => row.name) || [];
  const ensemble = result.summary.ensemble || summarizeEnsemble(targets, ruleSetNames);
  const complete = { ...result, summary: { ...result.summary, ensemble } };
  if (includeTargets) return complete;
  function boundedRows(rows, limit = sampleLimit) {
    const values = Array.isArray(rows) ? rows : [];
    return { samples: values.slice(0, limit), omitted: Math.max(0, values.length - limit) };
  }
  function compactTarget(target) {
    return {
      symbol: target.symbol,
      bytes: target.bytes,
      hasError: Boolean(target.error),
      variants: (target.variants || []).map((variant) => ({
        variant: variant.variant,
        status: variant.status,
        ...(variant.exactBytes ? { exactBytes: true, candidateId: variant.candidateId } : {}),
        ...(variant.error ? { hasError: true } : {}),
      })),
    };
  }
  const boundedEnsemble = {
    schemaVersion: ensemble.schemaVersion,
    baselineRuleSet: ensemble.baselineRuleSet,
    exactTargetCount: ensemble.exactTargetCount,
    exactSymbols: boundedRows(ensemble.exactSymbols),
    functionMembership: boundedRows(ensemble.functionMembership),
    ruleSets: ensemble.ruleSets.map((ruleSet) => ({
      name: ruleSet.name,
      exactCount: ruleSet.exactCount,
      matches: boundedRows(ruleSet.matches, 1),
      gainedVsBaseline: boundedRows(ruleSet.gainedVsBaseline, 1),
      lostVsBaseline: boundedRows(ruleSet.lostVsBaseline, 1),
      uniqueToRuleSet: boundedRows(ruleSet.uniqueToRuleSet, 1),
    })),
  };
  const selectorSymbols = Array.isArray(complete.selector?.symbols) ? complete.selector.symbols : null;
  const boundedSelector = selectorSymbols ? {
    ...complete.selector,
    symbols: undefined,
    symbolSamples: selectorSymbols.slice(0, sampleLimit),
    symbolsOmitted: Math.max(0, selectorSymbols.length - sampleLimit),
  } : complete.selector;
  const priorTargetSamples = Array.isArray(result.summary.targetSamples) ? result.summary.targetSamples : [];
  const targetSampleSource = hasTargets ? targets : priorTargetSamples;
  return {
    ...complete,
    selector: boundedSelector,
    summary: {
      ...complete.summary,
      ensemble: boundedEnsemble,
      targets: undefined,
      targetSamples: targetSampleSource.slice(0, sampleLimit).map(compactTarget),
      targetsOmitted: hasTargets
        ? Math.max(0, targets.length - sampleLimit)
        : (result.summary.targetsOmitted || 0) + Math.max(0, priorTargetSamples.length - sampleLimit),
    },
  };
}

function boundedContext(context, includeContext = false, rowLimit = 5) {
  if (includeContext) return context;
  function sample(name) {
    const rows = Array.isArray(context[name]) ? context[name] : [];
    return { rows: rows.slice(0, rowLimit), omitted: Math.max(0, rows.length - rowLimit) };
  }
  const runtime = context.runtime && {
    requested: context.runtime.requested,
    available: context.runtime.available,
    reviewState: context.runtime.reviewState || null,
    error: context.runtime.error || null,
    payloadOmitted: Boolean(context.runtime.payload),
  };
  return {
    schemaVersion: context.schemaVersion,
    contextId: context.contextId,
    target: context.target,
    summary: context.summary,
    arguments: context.arguments,
    fields: sample('fields'),
    callers: sample('callers'),
    callees: sample('callees'),
    returnWrites: sample('returnWrites'),
    runtime,
    evidenceBoundary: context.evidenceBoundary,
  };
}

function boundedEvidence(value, depth = 0) {
  if (Array.isArray(value)) {
    return {
      samples: value.slice(0, 3).map((item) => boundedEvidence(item, depth + 1)),
      omitted: Math.max(0, value.length - 3),
    };
  }
  if (!value || typeof value !== 'object') return value;
  if (depth >= 4) return '<nested evidence omitted>';
  return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, boundedEvidence(item, depth + 1)]));
}

function compactFrame(frame) {
  const offsets = Array.isArray(frame?.stackOffsets) ? frame.stackOffsets : [];
  return {
    frameSize: frame?.frameSize ?? null,
    stackOffsetCount: offsets.length,
    stackOffsetSamples: offsets.slice(0, 5),
    stackOffsetsOmitted: Math.max(0, offsets.length - 5),
  };
}

function compactMismatchLabel(label) {
  return {
    category: label.category,
    likelihood: label.likelihood,
    interpretation: label.interpretation,
    evidence: boundedEvidence(label.evidence),
    searchFamilies: (label.searchFamilies || []).slice(0, 4),
    avoidUntilResolved: (label.avoidUntilResolved || []).slice(0, 3),
  };
}

function compactRelocationEvidence(evidence) {
  if (!evidence) return null;
  function sourceSummary(source) {
    if (!source) return null;
    return {
      available: source.available,
      count: source.count,
      complete: source.complete,
      unavailableReason: source.unavailableReason || null,
      unknownKinds: (source.unknownKinds || []).slice(0, 4),
      unmaskableKnownKinds: (source.unmaskableKnownKinds || []).slice(0, 4),
      invalidRecordCount: (source.invalidRecords || []).length + (source.invalidRecordsOmitted || 0),
    };
  }
  const mismatch = evidence.mismatch && {
    expectedOnlyCount: evidence.mismatch.expectedOnlyCount,
    actualOnlyCount: evidence.mismatch.actualOnlyCount,
    identityMismatchCount: evidence.mismatch.identityMismatchCount,
    expectedOnlySamples: (evidence.mismatch.expectedOnlySamples || []).slice(0, 2),
    actualOnlySamples: (evidence.mismatch.actualOnlySamples || []).slice(0, 2),
    identityMismatchSamples: (evidence.mismatch.identityMismatchSamples || []).slice(0, 2),
  };
  return {
    expected: sourceSummary(evidence.expected),
    actual: sourceSummary(evidence.actual),
    comparisonAvailable: evidence.comparisonAvailable,
    recordsExact: evidence.recordsExact,
    addendIdentity: evidence.addendIdentity || null,
    mask: evidence.mask,
    mismatch,
  };
}

function compactMismatchEvidence(comparison) {
  const labels = Array.isArray(comparison?.labels) ? comparison.labels : [];
  return {
    differingInstructions: comparison?.differingInstructions ?? null,
    differingBytes: comparison?.differingBytes ?? null,
    mismatchCounts: comparison?.mismatchCounts || null,
    topLabels: labels.slice(0, 3).map(compactMismatchLabel),
    labelsOmitted: Math.max(0, labels.length - 3),
    relocationEvidence: compactRelocationEvidence(comparison?.relocationEvidence),
  };
}

function compactDiagnosticEvidence(comparison) {
  const raw = comparison?.rawObjectComparison;
  const diagnostic = comparison?.diagnostic;
  return {
    comparisonContract: comparison?.comparisonContract ?? null,
    evidenceMode: comparison?.evidenceMode || null,
    acceptanceEligible: comparison?.acceptanceEligible === true,
    rawObjectExactBytes: comparison?.rawExactBytes ?? raw?.exactBytes ?? null,
    rawObjectRelocationMaskedExact: comparison?.rawRelocationMaskedExact
      ?? raw?.relocationMaskedExact ?? null,
    diagnosticExactBytes: comparison?.diagnosticExactBytes ?? null,
    diagnosticRelocationMaskedExact: comparison?.diagnosticRelocationMaskedExact ?? null,
    rawObject: raw ? {
      primaryClass: raw.primaryClass,
      score: raw.score,
      cfgExact: raw.cfgExact,
      firstDifference: raw.firstDifference,
    } : null,
    diagnostic: diagnostic ? {
      status: diagnostic.status,
      mode: diagnostic.mode,
      code: diagnostic.code || null,
      reason: diagnostic.reason || null,
      control: diagnostic.control ? {
        linkedBytesSha256: diagnostic.control.linkedBytesSha256,
        durationMs: diagnostic.control.durationMs,
      } : null,
      candidate: diagnostic.candidate ? {
        linkedBytesSha256: diagnostic.candidate.linkedBytesSha256,
        durationMs: diagnostic.candidate.durationMs,
      } : null,
    } : null,
  };
}

function publicCandidateRecord(record, options = {}) {
  const candidate = {
    candidateId: record.candidate.candidate_id,
    targetId: record.candidate.target_id,
    sourceSha256: record.candidate.source_sha256,
    origin: record.candidate.origin,
    variant: record.candidate.variant,
    parentCandidateId: record.candidate.parent_candidate_id,
    metadata: record.candidate.metadata,
    createdAt: record.candidate.created_at,
  };
  if (options.includeSource) candidate.source = record.candidate.source_text;
  const runs = record.runs.map((run) => {
    const details = run.details || null;
    return {
      runId: run.run_id,
      status: run.status,
      sourceClass: run.source_class,
      primaryClass: run.primary_class,
      exactBytes: Boolean(run.exact_bytes),
      relocationMaskedExact: Boolean(run.relocation_masked_exact),
      score: run.score,
      durationMs: run.duration_ms,
      artifactDir: run.artifact_dir,
      createdAt: run.created_at,
      comparisonStale: Boolean(run.comparison_stale),
      ...(details ? compactMismatchEvidence(details) : {}),
      ...(details ? compactDiagnosticEvidence(details) : {}),
      ...(options.includeDetails ? { details, tool: run.tool, stderr: run.stderr } : {}),
    };
  });
  const observations = record.observations.map((observation) => ({
    observationId: observation.observation_id,
    origin: observation.origin,
    variant: observation.variant,
    parentCandidateId: observation.parent_candidate_id,
    metadata: observation.metadata,
    createdAt: observation.created_at,
  }));
  return { candidate, observations, runs, latestRun: runs[0] || null };
}

function compactComparison(comparison, includeDetails = false) {
  if (includeDetails) return comparison;
  return {
    schemaVersion: comparison.schemaVersion,
    ...compactDiagnosticEvidence(comparison),
    primaryClass: comparison.primaryClass,
    recommendation: comparison.recommendation,
    exactBytes: comparison.exactBytes,
    relocationMaskedExact: comparison.relocationMaskedExact,
    registerNormalizedExact: comparison.registerNormalizedExact,
    cfgExact: comparison.cfgExact,
    sameLength: comparison.sameLength,
    score: comparison.score,
    expectedBytes: comparison.expectedBytes,
    actualBytes: comparison.actualBytes,
    differingInstructions: comparison.differingInstructions,
    differingBytes: comparison.differingBytes,
    mismatchCounts: comparison.mismatchCounts,
    topLabels: (comparison.labels || []).slice(0, 3).map(compactMismatchLabel),
    labelsOmitted: Math.max(0, (comparison.labels || []).length - 3),
    relocationEvidence: compactRelocationEvidence(comparison.relocationEvidence),
    opcodeMatches: comparison.opcodeMatches,
    firstDifference: comparison.firstDifference,
    expectedFrame: compactFrame(comparison.expectedFrame),
    actualFrame: compactFrame(comparison.actualFrame),
  };
}

function initialize(workbench, options = {}) {
  const store = initializeStore();
  const targets = syncTargets(workbench, {}, { force: options.forceTargetSync === true });
  return { store, targets };
}

function comparisonSummary(result) {
  const comparison = result.comparison?.details || result.comparison;
  return {
    candidateId: result.candidate.candidateId,
    cached: result.cached,
    comparisonRefreshed: result.comparisonRefreshed === true,
    status: result.compile.status,
    sourceClass: result.compile.source_class || result.compile.sourceClass,
    primaryClass: comparison?.primaryClass || result.comparison?.primary_class || null,
    score: comparison?.score ?? result.comparison?.score ?? null,
    exactScratchBytes: comparison?.exactBytes ?? Boolean(result.comparison?.exact_bytes),
    diagnosticExactBytes: comparison?.diagnosticExactBytes ?? null,
    evidenceMode: comparison?.evidenceMode || null,
    rawObjectExactBytes: comparison?.rawExactBytes ?? comparison?.rawObjectComparison?.exactBytes ?? null,
    relocationMaskedExact: comparison?.relocationMaskedExact ?? Boolean(result.comparison?.relocation_masked_exact),
    ...compactMismatchEvidence(comparison),
    firstDifference: comparison?.firstDifference || null,
    recommendation: comparison?.recommendation || null,
    artifactDir: result.compile.artifact_dir || result.compile.artifactDir,
    acceptanceBoundary: 'Scratch results are research only; canonical linked target and full-ROM verification remain required.',
  };
}

function variantSelection(workbench, names) {
  if (!names || !names.length) return workbench.config.m2c.variants;
  const selected = workbench.config.m2c.variants.filter((variant) => names.includes(variant.name));
  const missing = names.filter((name) => !selected.some((variant) => variant.name === name));
  if (missing.length) throw new Error(`unknown m2c variant: ${missing.join(', ')}`);
  return selected;
}

function latestCandidateRun(candidateId) {
  const candidate = requestStore({ action: 'query', name: 'candidate', args: { candidateId } });
  if (!candidate) throw new Error(`candidate does not exist: ${candidateId}`);
  const runs = requestStore({ action: 'query', name: 'candidate_runs', args: {
    candidateId,
    limit: 20,
    ...comparisonQueryProvenance(),
  } });
  const observations = requestStore({ action: 'query', name: 'candidate_observations', args: { candidateId, limit: 20 } });
  return { candidate, observations, runs, run: runs.find((item) => item.status === 'compiled') || runs[0] || null };
}

function preserveCandidate(workbench, candidateId, note) {
  if (!note) throw new Error('preserve requires --note describing why the candidate is useful');
  const { candidate, run } = latestCandidateRun(candidateId);
  const target = workbench.targets.find((item) => item.targetId === candidate.target_id);
  if (!target) throw new Error('candidate belongs to a stale or unknown target model');
  const date = new Date().toISOString().slice(0, 10);
  const short = candidateId.slice(0, 10).toLowerCase();
  const sourceRelative = `docs/archive/matching-c-candidates/${date}-${target.symbol}-${short}.c`;
  const dossierRelative = `docs/dossiers/${target.symbol}-${short}.md`;
  const sourceFile = path.join(ROOT, ...sourceRelative.split('/'));
  const dossierFile = path.join(ROOT, ...dossierRelative.split('/'));
  if (fs.existsSync(sourceFile) || fs.existsSync(dossierFile)) throw new Error('preserved candidate output already exists');
  fs.mkdirSync(path.dirname(sourceFile), { recursive: true });
  fs.mkdirSync(path.dirname(dossierFile), { recursive: true });
  fs.writeFileSync(sourceFile, candidate.source_text, 'utf8');
  const comparison = run?.details || null;
  const lines = [
    `# ${target.symbol}: Preserved Matching-Workbench Candidate`,
    '',
    '## Status',
    '',
    'This source is a research candidate. The original assembly remains the accepted owner.',
    '',
    `- Candidate: \`${candidateId}\``,
    `- Target: \`${target.symbol}\` at ROM \`0x${target.romStart.toString(16).toUpperCase()}\``,
    `- Source: \`${sourceRelative}\``,
    `- Source SHA-256: \`${candidate.source_sha256}\``,
    `- Latest scratch class: \`${run?.primary_class || 'not compiled'}\``,
    `- Latest scratch score: \`${run?.score ?? 'not available'}\``,
    '',
    '## Preservation reason',
    '',
    note,
    '',
    '## Evidence boundary',
    '',
    'Scratch object comparison does not prove canonical linker ownership, relocation resolution, target bytes, or full-ROM identity. Resume through the normal diff and verification workflow.',
    '',
  ];
  if (comparison?.firstDifference) lines.push('## First recorded difference', '', '```json', JSON.stringify(comparison.firstDifference, null, 2), '```', '');
  fs.writeFileSync(dossierFile, lines.join('\n'), 'utf8');
  return { source: sourceRelative, dossier: dossierRelative };
}

async function main(argv = process.argv.slice(2)) {
  if (!argv.length || argv[0] === '--help' || argv[0] === '-h') { usage(); return; }
  const command = argv[0];
  const parsed = parseArgs(argv.slice(1));
  const { positional, options } = parsed;
  const workbench = loadWorkbenchModel();
  if (options['no-context'] && options['with-context']) throw new Error('--no-context and --with-context cannot be combined');
  if (options['no-context'] && options.runtime) throw new Error('--runtime requires context generation');
  if (command === 'doctor') {
    if (positional.length) throw new Error('doctor takes no positional arguments');
    const initialized = initialize(workbench, { forceTargetSync: true });
    const m2c = resolveM2c(workbench, { m2cRoot: options['m2c-root'] });
    const compiler = prepareCompilerSession();
    print({
      schemaVersion: 1,
      status: 'pass',
      modelId: workbench.modelId,
      acceptedFunctionTargets: workbench.targets.length,
      ordinaryTargets: workbench.targets.filter((target) => target.symbolByteOffset === 0).length,
      store: initialized,
      m2c: { root: m2c.root, commit: m2c.commit, tree: m2c.tree, untracked: m2c.untracked, target: workbench.config.m2c.target },
      compiler: compiler.tool,
      evidenceBoundary: 'The workbench prepares research candidates; canonical verification is unchanged.',
    }, options);
    return;
  }
  initialize(workbench);
  if (command === 'inspect') {
    if (positional.length !== 1) throw new Error('inspect requires one symbol');
    const target = resolveTarget(workbench, positional[0]);
    const families = requestStore({ action: 'query', name: 'families_for_target', args: { targetId: target.targetId, limit: numeric(options.limit, '--limit', 20) } });
    const history = requestStore({ action: 'query', name: 'history', args: {
      modelId: workbench.modelId,
      symbol: target.symbol,
      limit: 5,
      ...comparisonQueryProvenance(),
    } });
    print({ target: publicTarget(target), metrics: targetMetrics(target.expectedBytes, target.vramStart), families, recentExperiments: history }, options);
    return;
  }
  if (command === 'history' || command === 'best') {
    if (positional.length !== 1) throw new Error(`${command} requires one symbol`);
    const target = resolveTarget(workbench, positional[0]);
    const storedRows = requestStore({ action: 'query', name: command, args: {
      modelId: workbench.modelId,
      symbol: target.symbol,
      limit: numeric(options.limit, '--limit', 20),
      includeDetails: true,
      ...comparisonQueryProvenance(),
    } });
    const rows = storedRows.map((row) => {
      if (!row.details) return row;
      const { details, ...summary } = row;
      return {
        ...summary,
        ...compactMismatchEvidence(details),
        ...compactDiagnosticEvidence(details),
        ...(options['include-details'] ? { details } : {}),
      };
    });
    print({ symbol: target.symbol, count: rows.length, rows }, options);
    return;
  }
  if (command === 'watch') {
    if (positional.length !== 1 || !options.source) throw new Error('watch requires <symbol> --source <candidate.c>');
    const target = resolveTarget(workbench, positional[0]);
    const sourceFile = path.resolve(options.source);
    const result = compileCandidate(workbench, target, fs.readFileSync(sourceFile, 'utf8'), {
      origin: 'manual-watch',
      metadata: { sourcePath: portableSourcePath(sourceFile) },
      syncTargets: false,
    });
    print(comparisonSummary(result), options);
    if (result.compile.status !== 'compiled') process.exitCode = 2;
    return;
  }
  if (command === 'classify') {
    if (positional.length !== 1) throw new Error('classify requires one candidate id');
    const record = latestCandidateRun(positional[0]);
    print(publicCandidateRecord(record, { includeSource: options['include-source'], includeDetails: options['include-details'] }), options);
    return;
  }
  if (command === 'compare') {
    if (positional.length !== 2) throw new Error('compare requires two candidate ids');
    const left = latestCandidateRun(positional[0]);
    const right = latestCandidateRun(positional[1]);
    if (!left.run?.object_text || !right.run?.object_text) throw new Error('both candidates require successful object compilations');
    if (left.candidate.target_id !== right.candidate.target_id) throw new Error('candidate comparison requires the same exact target identity');
    const target = workbench.targets.find((item) => item.targetId === left.candidate.target_id);
    if (!target) throw new Error('candidate comparison requires a target in the currently accepted model');
    const leftRelocationsAvailable = Array.isArray(left.run.relocations);
    const rightRelocationsAvailable = Array.isArray(right.run.relocations);
    const comparison = compareMips(Buffer.from(left.run.object_text, 'base64'), Buffer.from(right.run.object_text, 'base64'), {
      start: target.vramStart,
      expectedRelocations: left.run.relocations,
      expectedRelocationsAvailable: leftRelocationsAvailable,
      expectedRelocationsUnavailableReason: leftRelocationsAvailable ? undefined : 'left candidate relocation evidence is unavailable',
      actualRelocations: right.run.relocations,
      actualRelocationsAvailable: rightRelocationsAvailable,
      actualRelocationsUnavailableReason: rightRelocationsAvailable ? undefined : 'right candidate relocation evidence is unavailable',
      symbolicControlFlow: true,
      symbolicExpectedControlFlow: true,
    });
    print({
      left: { candidateId: positional[0], runId: left.run.run_id, createdAt: left.run.created_at, compilerSha256: left.run.tool?.compilerSha256 },
      right: { candidateId: positional[1], runId: right.run.run_id, createdAt: right.run.created_at, compilerSha256: right.run.tool?.compilerSha256 },
      comparison: compactComparison(comparison, options['include-details']),
      evidenceBoundary: 'Candidate comparison uses raw objects plus symbolic relocation-aware CFG evidence; it does not prove linked addresses or matching acceptance.',
    }, options);
    return;
  }
  if (command === 'case-cfg') {
    if (positional.length !== 1 || !options['case-map']) {
      throw new Error('case-cfg requires <candidate-id> --case-map <map.json>');
    }
    if (options['actual-dispatch'] === undefined || options['actual-body'] === undefined) {
      throw new Error('case-cfg requires --actual-dispatch and --actual-body');
    }
    const record = latestCandidateRun(positional[0]);
    if (!record.run?.object_text) throw new Error('case-cfg requires a successfully compiled candidate');
    const target = workbench.targets.find((item) => item.targetId === record.candidate.target_id);
    if (!target) throw new Error('case-cfg candidate target is stale or absent from the accepted model');
    const mapFile = path.resolve(options['case-map']);
    const map = JSON.parse(fs.readFileSync(mapFile, 'utf8'));
    if (![1, 2].includes(map.schemaVersion) || map.symbol !== target.symbol || !Array.isArray(map.commands)) {
      throw new Error('case-cfg map does not match the candidate target or supported schema');
    }
    const candidateContract = resolveCandidateComparisonContract(map, positional[0]);
    if (candidateContract?.sourceSha256
        && candidateContract.sourceSha256.toUpperCase() !== String(record.candidate.source_sha256 || '').toUpperCase()) {
      throw new Error(`case-cfg candidate source identity differs from tracked contract for ${positional[0]}`);
    }
    if (candidateContract?.sourceClass && candidateContract.sourceClass !== record.run.source_class) {
      throw new Error(`case-cfg candidate source class differs from tracked contract for ${positional[0]}`);
    }
    const actualTails = actualTailMap(options['actual-tail']);
    if (!actualTails.length) throw new Error('case-cfg requires at least one --actual-tail name=offset mapping');
    const actualBuffer = Buffer.from(record.run.object_text, 'base64');
    const trackedActualDispatch = candidateContract?.actualDispatch || {};
    const actualDispatch = {
      dispatchOffset: nonnegativeInteger(options['actual-dispatch'], '--actual-dispatch'),
      bodyOffset: nonnegativeInteger(options['actual-body'], '--actual-body'),
      valueRegister: nonnegativeInteger(
        trackedActualDispatch.valueRegister ?? map.actualValueRegister ?? map.expectedDispatch.valueRegister,
        'actual value register'),
      initialRegisters: trackedActualDispatch.initialRegisters
        || map.actualInitialRegisters || map.expectedDispatch.initialRegisters,
      localJumpMode: trackedActualDispatch.localJumpMode || 'section-relative',
      ...(trackedActualDispatch.maximumSteps === undefined ? {} : { maximumSteps: trackedActualDispatch.maximumSteps }),
    };
    assertCandidateComparisonInputs(candidateContract, actualDispatch, actualTails, actualBuffer.length);
    const symbolForAddress = (address) => {
      const matches = workbench.targets.filter((item) => item.entryVram === (address >>> 0));
      if (matches.length === 1) return matches[0].symbol;
      return `func_${(address >>> 0).toString(16).toUpperCase().padStart(8, '0')}`;
    };
    const report = compareCaseCfg(target.expectedBytes, actualBuffer, {
      start: target.vramStart,
      symbol: target.symbol,
      commands: map.commands,
      expectedDispatch: map.expectedDispatch,
      actualDispatch,
      expectedTails: map.expectedTails,
      actualTails,
      actualRelocations: record.run.relocations || [],
      symbolForAddress,
      candidate: {
        candidateId: positional[0],
        runId: record.run.run_id,
        sourceClass: record.run.source_class,
      },
    });
    assertCandidateComparisonResult(candidateContract, report);
    report.caseMap = path.relative(ROOT, mapFile).replace(/\\/g, '/');
    const defaultOutput = path.join(ROOT, 'build', 'matching', 'case-cfg', target.symbol, `${positional[0].slice(0, 12)}.json`);
    const outputFile = options.output ? path.resolve(options.output) : defaultOutput;
    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, `${JSON.stringify(report, null, 2)}\n`);
    print(options['include-details'] ? report : {
      schemaVersion: report.schemaVersion,
      target: report.target,
      candidate: report.candidate,
      comparisonContract: report.comparisonContract,
      commandCount: report.commandCount,
      summary: report.summary,
      resultDigest: report.resultDigest,
      mismatchedCommands: report.commands.filter((row) => !Object.values(row.parity).every(Boolean)).slice(0, 30)
        .map((row) => ({ command: row.command, expectedBlocks: row.expected.blockCount, actualBlocks: row.actual.blockCount, parity: row.parity })),
      mismatchedCommandsOmitted: Math.max(0, report.commandCount - report.summary.exactStructuralCommands - 30),
      report: path.relative(ROOT, outputFile).replace(/\\/g, '/'),
      evidenceBoundary: report.evidenceBoundary,
    }, options);
    return;
  }
  if (command === 'preserve') {
    if (positional.length !== 1) throw new Error('preserve requires one candidate id');
    print(preserveCandidate(workbench, positional[0], options.note), options);
    return;
  }
  if (command === 'prepare') {
    if (positional.length !== 1) throw new Error('prepare requires one symbol');
    const target = resolveTarget(workbench, positional[0]);
    const compilerSession = options['no-compile'] ? null : prepareCompilerSession();
    const contextIndex = options['no-context'] ? null : buildContextIndex(workbench);
    const result = prepareAndCompile(workbench, target, {
      variants: variantSelection(workbench, options.variant),
      compile: !options['no-compile'],
      generateContext: !options['no-context'],
      useContext: options['with-context'] === true,
      runtimeContext: options.runtime,
      contextIndex,
      compilerSession,
      m2cRoot: options['m2c-root'],
      syncTargets: false,
    });
    print({
      symbol: target.symbol,
      assemblyFile: path.relative(ROOT, result.assemblyFile).replace(/\\/g, '/'),
      contextFile: result.contextFile ? path.relative(ROOT, result.contextFile).replace(/\\/g, '/') : null,
      generation: result.results.map((item) => ({
        variant: item.variant,
        ok: item.ok,
        durationMs: item.durationMs,
        sourceFile: path.relative(ROOT, item.sourceFile).replace(/\\/g, '/'),
        diagnostics: item.diagnostics,
        failure: item.failure,
        stderr: item.stderr,
      })),
      compilations: result.compilations.map((item) => item.result ? { variant: item.variant, ...comparisonSummary(item.result) } : item),
    }, options);
    return;
  }
  if (command === 'sweep') {
    if (positional.length) throw new Error('sweep uses options rather than positional targets');
    const selector = {
      set: options.set || null,
      maxSize: numeric(options['max-size'], '--max-size'),
      leafOnly: Boolean(options['leaf-only']),
      ...(options['include-solved'] ? { includeSolved: true } : {}),
      limit: numeric(options.limit, '--limit'),
    };
    const result = await runSweep(workbench, selector, {
      variantNames: options.variant,
      jobs: numeric(options.jobs, '--jobs', 1),
      compile: !options['no-compile'],
      generateContext: !options['no-context'],
      useContext: options['with-context'] === true,
      runtimeContext: options.runtime,
      m2cRoot: options['m2c-root'],
      onProgress: options.json ? null : (status) => console.log(`[${status.processed}/${status.selected}] ${status.current}: exact=${status.exactBytes} compiled=${status.compileSucceeded} failed=${status.failed}`),
    });
    print(boundedSweepResult(result, options['include-targets'] === true), options);
    return;
  }
  if (command === 'sweep-status') {
    if (positional.length) throw new Error('sweep-status takes no positional arguments');
    const includeTargets = options['include-targets'] === true;
    const sweepProvenance = comparisonQueryProvenance();
    const storedSweeps = requestStore({
      action: 'query',
      name: 'sweeps',
      args: {
        modelId: workbench.modelId,
        limit: numeric(options.limit, '--limit', 20),
        includeTargets,
        targetLimit: 5,
        ...sweepProvenance,
      },
    });
    const sweeps = storedSweeps.map((sweep) => {
      if (includeTargets || sweep.summary?.ensemble) return boundedSweepResult(sweep, includeTargets, 5);
      const complete = requestStore({ action: 'query', name: 'sweep_by_id', args: {
        sweepId: sweep.sweep_id,
        ...sweepProvenance,
      } });
      return boundedSweepResult(complete, false, 5);
    });
    print({
      modelId: workbench.modelId,
      sweeps,
    }, options);
    return;
  }
  if (command === 'family') {
    if (positional[0] === 'build') {
      if (positional.length !== 1) throw new Error('family build takes no other positional arguments');
      const result = buildFamilyAtlas(workbench);
      print({ modelId: result.modelId, counts: result.counts, stored: result.stored }, options);
      return;
    }
    if (positional[0] === 'list') {
      const rows = requestStore({ action: 'query', name: 'family_list', args: {
        modelId: workbench.modelId,
        tier: options.tier || null,
        limit: numeric(options.limit, '--limit', 20),
        includeMembers: options['include-members'] === true,
        memberLimit: 5,
      } });
      print({ modelId: workbench.modelId, count: rows.length, rows }, options);
      return;
    }
    if (positional.length !== 1) throw new Error('family requires build, list, or one symbol');
    const target = resolveTarget(workbench, positional[0]);
    const families = requestStore({ action: 'query', name: 'families_for_target', args: {
      targetId: target.targetId,
      limit: numeric(options.limit, '--limit', 20),
      includeMembers: options['include-members'] === true,
      memberLimit: 5,
    } });
    print({ symbol: target.symbol, targetId: target.targetId, families }, options);
    return;
  }
  if (command === 'context') {
    if (positional.length !== 1) throw new Error('context requires one symbol');
    const target = resolveTarget(workbench, positional[0]);
    const context = storeTargetContext(workbench, target, { runtime: options.runtime, syncTargets: false });
    print(boundedContext(context, options['include-context'] === true), options);
    return;
  }
  if (command === 'rank') {
    if (positional.length) throw new Error('rank uses --lane or --explain');
    if (options.lane && !['leverage', 'batch', 'hard-tail'].includes(options.lane)) throw new Error('unknown rank lane');
    const report = rankTargets(workbench, {
      lane: options.lane || null,
      limit: options.explain ? workbench.targets.length : numeric(options.limit, '--limit', 20),
      skipFamilies: options['skip-families'],
      includeDetails: Boolean(options.explain),
      comparisonCurrentFingerprint: comparisonQueryProvenance().diagnosticCurrentFingerprint,
      comparisonEnvironmentId: comparisonQueryProvenance().diagnosticEnvironmentId,
    });
    if (options.explain) {
      const selected = report.entries.find((item) => item.symbol.toLowerCase() === options.explain.toLowerCase());
      if (!selected) throw new Error(`rank target does not resolve: ${options.explain}`);
      print(selected, options);
    } else print(report, options);
    return;
  }
  if (command === 'probe') {
    if (positional[0] === 'compare') {
      if (positional.length !== 3) throw new Error('probe compare requires two probe report paths');
      print(compareProbes(positional[1], positional[2]), options);
      return;
    }
    if (positional.length !== 1) throw new Error('probe requires one symbol');
    const target = resolveTarget(workbench, positional[0]);
    let sourceText;
    if (options.source) sourceText = fs.readFileSync(path.resolve(options.source), 'utf8');
    else if (options.candidate) sourceText = latestCandidateRun(options.candidate).candidate.source_text;
    else if (target.activeMatchingSource) sourceText = fs.readFileSync(path.join(ROOT, ...target.activeMatchingSource.split('/')), 'utf8');
    else throw new Error('probe requires --source or --candidate for a target without active matching C');
    const passes = options.passes ? options.passes.split(',').map((item) => item.trim()).filter(Boolean) : null;
    print(runProbe(workbench, target, sourceText, { passes, researchCompiler: options['research-compiler'] }), options);
    return;
  }
  throw new Error(`unknown matching workbench command: ${command}`);
}

if (require.main === module) {
  main().catch((error) => {
    console.error(`Matching workbench failed: ${error.message}`);
    process.exitCode = 1;
  });
}

module.exports = {
  boundedContext,
  boundedSweepResult,
  compactComparison,
  compactMismatchEvidence,
  compactRelocationEvidence,
  comparisonSummary,
  main,
  parseArgs,
  portableSourcePath,
  preserveCandidate,
  publicCandidateRecord,
};
